local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local trainstationutil = require "modules/trainstationutil"

function data()

return { 
	availability = {
		yearFrom = 0,
		yearTo = 0,
	},
	cost = {
		price = 18000,
	},
	description = {
		name = _("Standard tracks 80"),
		description = _("Standard tracks with limited speed capabilities. 80"),
		icon = "ui/tracks/standard_80.tga"
	},
	type = "track",
	order = {
		value = 208,
	},
	metadata = {
		track = true,
	},
	category = {
		categories = { "tracks", },
	},
	--buildMode = "MULTI",
	
	updateFn = function(result, transform, tag, slotId, addModuleFn, params)
		local edgeListNum = trainstationutil.findOrMakeNewEdgeListNum(result, "standard_gedreht_80.lua", false)
		trainstationutil.makeTrack(result, transform, tag, slotId, addModuleFn, params, edgeListNum)
	end,
	
	getModelsFn = function()
		
		local result = {
		}
		
		return result
	end
}

end
