local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local trainstationutil = require "modules/trainstationutil"

function data()

return { 
	availability = {
		yearFrom = 1925,
		yearTo = 0,
	},
	cost = {
		price = 40000,
	},
	category = {
		categories = { "tracks", },
	},
	description = {
		name = _("High-speed tracks with catenary lzb 300"),
		description = _("Specialized tracks with catenary for higher speeds. lzb 300"),
		icon = "ui/tracks/alternativ/high_speed_lzb_gedreht.tga"
	},
	-- buildMode = "MULTI",
	type = "track",
	order = {
		value = 283,
	},
	metadata = {
		track = true,
	},
	
	updateFn = function(result, transform, tag, slotId, addModuleFn, params)
		local edgeListNum = trainstationutil.findOrMakeNewEdgeListNum(result, "alternativ/high_speed_lzb_gedreht.lua", true)
		trainstationutil.makeTrack(result, transform, tag, slotId, addModuleFn, params, edgeListNum)
	end,
	
	getModelsFn = function()
		
		local result = {
		}
		
		return result
	end
}

end
